Nigel.RazorTests/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nigel.RazorTests
{
    public class CreateModel : PageModel
    {
        TestDBContext _dbContext;
        public CreateModel(TestDBContext context)
        {
            _dbContext = context;
        }

        [BindProperty]
        public Customer Customer { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _dbContext.AddAsync(Customer);

            if (await _dbContext.SaveChangesAsync() > 0)
            {
                return RedirectToPage("index");
            }

            return Page();
        }
    }
}

Nigel.RazorTests/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Nigel.RazorTests
{
    public class EditModel : PageModel
    {
        TestDBContext _dbContext;
        public EditModel(TestDBContext context)
        {
            _dbContext = context;
        }

        [BindProperty]
        public Customer Customer { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Customer = await _dbContext.Customer.FirstOrDefaultAsync(c => c.Id == id);
            if (Customer == null)
                return RedirectToPage("index");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Attach(Customer).State = EntityState.Modified;

            if (await _dbContext.SaveChangesAsync() > 0)
            {
                return RedirectToPage("index");
            }

            return Page();
        }
    }
}

Nigel.RazorTests/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Nigel.RazorTests.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Nigel.RazorTests/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Nigel.RazorTests.Pages
{
    public class IndexModel : PageModel
    {
        private readonly TestDBContext _dbContext;
        public IndexModel(TestDBContext context)
        {
            _dbContext = context;
        }

        [BindProperty(SupportsGet = true)]
        public int id { get; set; }

        public IList<Customer> Customers;

        public async Task OnGetAsync()
        {
            Customers = await _dbContext.Customer.ToListAsync();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var entity = await _dbContext.Customer.FirstOrDefaultAsync(c => c.Id == id);

            if (entity != null)
            {
                _dbContext.Customer.Remove(entity);
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage();
        }

    }
}

Nigel.RazorTests/Pages/IndexView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Nigel.RazorTests.Pages
{
    public class IndexViewModel : PageModel
    {
        private readonly TestDBContext _dbContext;
        public IndexViewModel(TestDBContext context)
        {
            _dbContext = context;
        }

        public IList<Customer> Customers;

        public async Task OnGetAsync(int id)
        {
            Customers = await _dbContext.Customer.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete2Async(int id)
        {
            var entity = await _dbContext.Customer.FirstOrDefaultAsync(c => c.Id == id);

            if (entity != null)
            {
                _dbContext.Customer.Remove(entity);
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage();
        }

    }
}

Nigel.RazorTests/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Nigel.RazorTests.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Nigel.RazorTests/Pages/Create.cshtml
@page
@model Nigel.RazorTests.CreateModel

<p>Validation: customer name:</p>

<form method="post">
    <div asp-validation-summary="All"></div>
    Name:
    <input asp-for="Customer.Name" />
    <span asp-validation-for="Customer.Name"></span>
    <input type="submit" />
</form>

Nigel.RazorTests/Pages/Edit.cshtml
@page "{id:int?}"
@model Nigel.RazorTests.EditModel

<p>Validation: customer name:</p>

<form method="post">
    <input asp-for="Customer.Id" type="hidden" />
    <div asp-validation-summary="All"></div>
    Name:
    <input asp-for="Customer.Name" />
    <span asp-validation-for="Customer.Name"></span>
    <input type="submit" />
</form>

Nigel.RazorTests/Pages/Index.cshtml
@page "{id?}"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        @using (Html.BeginForm(FormMethod.Post))
        {
            <table>
                <thead>
                    <tr>
                        <td>Id</td>
                        <td>Name</td>
                        <td>修改</td>
                        <td>删除</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Customers)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td><a asp-page="edit" asp-route-id="@item.Id">修改</a></td>
                            <td><button type="submit" asp-page-handler="delete" asp-route-id="@item.Id">删除</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </p>
    <p><a asp-page="create">添加</a></p>
</div>
@section Scripts{
    <script type="text/javascript">
        $(function () {

            //$.post('?handler=delete', { id: 1 })
            //    .then(function (res) {
            //        console.log(res);
            //    })
            //    .fail(function (res) {
            //        alert(res);
            //    });

        })
    </script>
}

Nigel.RazorTests/Pages/IndexView.cshtml
@page
@model IndexViewModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        @using (Html.BeginForm(FormMethod.Post))
        {
            <table>
                <thead>
                    <tr>
                        <td>Id</td>
                        <td>Name</td>
                        <td>修改</td>
                        <td>删除</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Customers)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td><a asp-page="edit" asp-route-id="@item.Id">修改</a></td>
                            <td><button type="submit" asp-page-handler="delete2" asp-route-id="@item.Id">删除</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </p>
    <p><a asp-page="create">添加</a></p>
</div>

Nigel.RazorTests/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nigel.RazorTests</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Nigel.RazorTests</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Nigel.RazorTests - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>